---
apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane-config
data:
  config.yaml: |
    server:
      host: 0.0.0.0
      port: 3000
      {{- if .Values.headplane.config.url }}
      base_url: {{ .Values.headplane.config.url }}
      {{- end }}
      cookie_secret_path: /var/secrets/headplane/server/{{ .Values.headplane.config.cookieSecret.secretKey }}
      cookie_secure: true
    headscale:
      url: http://127.0.0.1:8080
      {{- if .Values.headscale.config.url }}
      public_url: {{ .Values.headscale.config.url }}
      {{- end }}
      api_key_path: /var/secrets/headplane/headscale/{{ .Values.headplane.config.headscaleApiKey.secretKey }}
      config_path: /etc/headscale/config.yaml
      config_strict: true
    integration:
      kubernetes:
        enabled: true
        validate_manifest: true
        pod_name: replaced-by-environment-variable
    {{- if .Values.headplane.config.oidc.enabled }}
    oidc:
      issuer: {{ .Values.headplane.config.oidc.issuerUrl }}
      client_id: {{ .Values.headplane.config.oidc.clientId }}
      client_secret_path: /var/secrets/headplane/oidc/{{ .Values.headplane.config.oidc.clientSecret.secretKey }}
      disable_api_key_login: {{ .Values.headplane.config.oidc.disableApiKeyLogin }}
      use_pkce: {{ .Values.headplane.config.oidc.usePkce }}
      {{- if .Values.headplane.config.oidc.tokenEndpointAuthMethod }}
      token_endpoint_auth_method: {{ .Values.headplane.config.oidc.tokenEndpointAuthMethod }}
      {{- end }}
    {{- end }}
