{{- if not .Values.headplane.config.cookieSecret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headplane-cookie-secret
stringData:
  {{ .Values.headplane.config.cookieSecret.secretKey }}: {{ include "headplane.cookieSecret" . }}
{{- end }}
{{- if and (not .Values.headplane.config.headscaleApiKey.secretName) (not .Values.headplane.config.generateCredentials) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headscale-api-key
stringData:
  {{ .Values.headplane.config.headscaleApiKey.secretKey }}: {{ required "headplane.config.headscaleApiKey.value is required when secretName is not set and generateCredentials is false" .Values.headplane.config.headscaleApiKey.value }}
{{- end }}
{{- if .Values.headplane.config.oidc.enabled }}
{{- if not .Values.headplane.config.oidc.clientSecret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headplane-oidc-client-secret
stringData:
  {{ .Values.headplane.config.oidc.clientSecret.secretKey }}: {{ required "headplane.config.oidc.clientSecret.value is required when secretName is not set" .Values.headplane.config.oidc.clientSecret.value }}
{{- end }}
{{- end }}
