{{- if and .Values.headscale.config.oidc.enabled (not .Values.headscale.config.oidc.clientSecret.secretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headscale-oidc-client-secret
stringData:
  {{ .Values.headscale.config.oidc.clientSecret.secretKey }}: {{ required "headscale.config.oidc.clientSecret.value is required when secretName is not set" .Values.headscale.config.oidc.clientSecret.value }}
{{- end }}
{{- if eq .Values.headscale.config.database.type "postgres" }}
{{- if not .Values.headscale.config.database.postgres.password.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headscale-db-password
stringData:
  {{ .Values.headscale.config.database.postgres.password.secretKey }}: {{ required "headscale.config.database.postgres.password.value is required when secretName is not set" .Values.headscale.config.database.postgres.password.value }}
{{- end }}
{{- end }}
