---
apiVersion: v1
kind: Service
metadata:
  name: headscale
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: grpc
      port: 50443
      protocol: TCP
      targetPort: 50443
    - name: stun
      port: 3478
      protocol: UDP
      targetPort: 3478
  selector:
    app: headplane
  type: ClusterIP
