{{- if .Values.stun.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: headscale-stun
  {{- if .Values.stun.annotations }}
  annotations:
    {{- toYaml .Values.stun.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.stun.type }}
  {{- if .Values.stun.loadBalancerIP }}
  loadBalancerIP: {{ .Values.stun.loadBalancerIP }}
  {{- end }}
  ports:
    - name: stun
      port: {{ .Values.stun.port }}
      protocol: UDP
      targetPort: {{ .Values.stun.port }}
  selector:
    app: headplane
{{- end }}
